### ISSUE TITLE
[BUG] Package subpath './utilities' is not defined by "exports" in "../node_modules/warframe-items/package.json"

### ISSUE THREAD

**Issue by fburaktrd** [WFCD/warframe-items#630]
### Describe the bug

Package subapath './utilities' is not defined by "exports" in "../node_modules/warframe-items/package.json"

### NodeJS Version

v20.4.0

### npm Version

v9.7.2

### warframe-items Version

v1.1263.9

### Access Method

npm Package (Default)

### What happened?

Hi!

I've recently added a package to my NestJs application but encountered a runtime error when trying to import the 'find' module from the warframe-items/utilities package.

I followed the documentation and attempted to import the method using the following code:
```TypeScript 
import { find } from 'warframe-items/utilities';
```

However, I received the following error:
```
node:internal/modules/cjs/loader:553
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utilities' is not defined by "exports" in **/node_modules/warframe-items/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:260:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:534:13)
    at resolveExports (node:internal/modules/cjs/loader:547:36)
    at Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (**/src/resources/profile/profile.service.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/**/src/app.module.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (**/src/main.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.4.0
```
It seems like the package's subpath './utilities' is not defined in the "exports" field of the warframe-items/package.json file. Am I missing something here? Any advice would be greatly appreciated! Thanks in advance!

**Comment by SlayerOrnstein** [comment]
Have you tried deleting `node_modules` and running `npm install` again?

**Comment by TobiTenno** [comment]
also, you can't use utilities from cjs, you have to be on ESM to use it. i can see that you're trying to resolve it in the cjs loader but the esm resolver

**Comment by fburaktrd** [comment]
Hey @TobiTenno, thanks for the clarification! That definitely explains the issue. Unfortunately, I just found out that NestJS doesn't support ESM yet, according to this [thread](https://github.com/nestjs/nest/issues/13319), so I’m unable to use this package in my NestJS project.

Since the codebase is private, I can't share the source code, but you can easily reproduce the issue by creating a new NestJS app and trying to install warframe-items. Do you think there’s any way to make this package work with CJS as well?

**Comment by TobiTenno** [comment]
to be clear, warframe-items works fine with cjs, it's specifically the utilities subpackage that doesn't work.

you can still use the functionality of the utilities, but i didn't want to back-port those to commonjs. you're welcome to backport them if you'd like, we're opensource, i just don't have a plan to do so right now.

**Comment by fburaktrd** [comment]
I would definitely like to try that. When I used it as you mentioned, it worked. I really appreciate it.

**Comment by TobiTenno** [comment]
cool! if you want to try porting it, i'll happily review and speed your change through
